info:
  app:
    name: 'F1DBApp'
    version: '1.0.0'
    grailsVersion: '5.3.2'

grails:
  profile: web
  codegen:
    defaultPackage: com.example

  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none

  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml

  mongodb:
    url: "mongodb+srv://oriol:admin@f1db.eunnphy.mongodb.net/?retryWrites=true&w=majority&appName=F1DB" # ✅ Usa variable de entorno, más seguro

  plugin:
    springsecurity:
      successHandler:
        defaultTargetUrl: '/home/index'
      userLookup:
        userDomainClassName: com.example.Usuario
        usernamePropertyName: username
        passwordPropertyName: password
      authority:
        className: com.example.Rol
      userLookup.authorityJoinClassName: null  # ✅ No usar UsuarioRol con MongoDB

      controllerAnnotations:
        staticRules:
          - pattern: '/home/index'
            access: [ 'ROLE_USER' ]
          - pattern: '/team/**'
            access: [ 'ROLE_USER' ]
          - pattern: '/team/**/**'
            access: [ 'ROLE_USER' ]
          - pattern: '/team/show'
            access: [ 'ROLE_USER' ]
          - pattern: '/raceresults/raceresults'
            access: [ 'ROLE_USER' ]
          - pattern: '/radio/index'
            access: [ 'ROLE_USER' ]
          - pattern: '/radio/**'
            access: [ 'ROLE_USER' ]
          - pattern: '/radio/results'
            access: [ 'ROLE_USER' ]
          - pattern: '/favicon.ico'
            access: [ 'ROLE_USER' ]
          - pattern: '/calendarioF1/index'
            access: [ 'ROLE_USER' ]
          - pattern: '/calendarioF1/result'
            access: [ 'ROLE_USER' ]
          - pattern: '/calendarioF1/**'
            access: [ 'ROLE_USER' ]
          - pattern: '/'
            access: [ 'permitAll' ]
          - pattern: '/login/**'
            access: [ 'permitAll' ]
          - pattern: '/logout/**'
            access: [ 'permitAll' ]
          - pattern: '/login/register'
            access: [ 'permitAll' ]
          - pattern: '/login/registrar'
            access: [ 'permitAll' ]
          - pattern: '/assets/**'
            access: [ 'permitAll' ]
          - pattern: '/**/js/**'
            access: [ 'permitAll' ]
          - pattern: '/**/css/**'
            access: [ 'permitAll' ]
          - pattern: '/**/images/**'
            access: [ 'permitAll' ]
