info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
  mongodb:
    uri: "mongodb+srv://atlas-sample-dataset-load-67f549479a6e87041dae0a9e:csierra2210@cluster0.lxup28u.mongodb.net/miapp?retryWrites=true&w=majority&appName=Cluster0"
  plugin:
    springsecurity:
      userLookup:
        userDomainClassName: com.example.Usuario
        usernamePropertyName: username
        passwordPropertyName: password
      authority:
        className: com.example.Rol
      controllerAnnotations:
        staticRules:
          - pattern: '/'
            access: [ 'permitAll' ]
          - pattern: '/index'
            access: [ 'permitAll' ]
          - pattern: '/index.gsp'
            access: [ 'permitAll' ]
          - pattern: '/assets/**'
            access: [ 'permitAll' ]
          - pattern: '/**/js/**'
            access: [ 'permitAll' ]
          - pattern: '/**/css/**'
            access: [ 'permitAll' ]
          - pattern: '/**/images/**'
            access: [ 'permitAll' ]
          - pattern: '/favicon.ico'
            access: [ 'permitAll' ]
          - pattern: '/usuario/register'
            access: [ 'permitAll' ]
          - pattern: '/usuario/registrar'
            access: [ 'permitAll' ]

  codegen:
    defaultPackage: com.example
  profile: web
